const subjects = [
    "Physics",
    "Chemistry",
    "Mathematics",
    "English Proficiency",
    "Logical Reasoning",
    "English",
    "Aptitude",
    "General Knowledge",
    "Current Affairs including General Knowledge",
    "Legal Reasoning",
    "Logical Reasoning",
    "Quantitative Techniques",
    "Biology (Botany and Zoology)",
    "General Awareness and Current Affairs",
    "Common Legal Knowledge",
    "Aptitude and Mental Ability",
    "Verbal Ability and Reading Comprehension",
    "Data Interpretation and Logical Reasoning",
    "Quantitative Ability",
    "Engineering Mathematics",
    "Subject-Specific Section",
    "Verbal Reasoning",
    "Quantitative Reasoning",
    "Analytical Writing",
    "Specific Area (as per the course)",
    "Decision Making",
    "General Ability Test (English, General Knowledge)",
    "Constitutional Law",
    "Jurisprudence",
    "Other Law Subjects",
    "Pre and Para Clinical Subjects",
    "Clinical Subjects",
    "Forensic Medicine",
    "Visual Perception Ability",
    "Environmental and Social Awareness",
    "Language and Creativity Skills",
    "Drawing Skills",
    "Creativity",
    "Analytical and Comprehension Skills",
    "General Ability Test",
    "Creative Ability Test",
    "Situation Test",
    "General Studies",
    "Civil Services Aptitude Test (CSAT)",
    "Main Exam - 9 papers including Essay and Optional subjects",
    "Interview",
    "General Intelligence and Reasoning",
    "Quantitative Aptitude",
    "Reasoning Ability",
    "General Awareness (for SO)",
    "Mathematics",
    "Child Development and Pedagogy",
    "Language I and II",
    "Environmental Studies",
    "Mechanical",
    "Electronics",
    "Computer Science",
    "Electrical",
    "Civil",
    "Insurance and Financial Market Awareness"
  ];
  export default subjects